# Generated by Django 3.0.8 on 2020-08-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='priceType',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
