# Generated by Django 3.0.8 on 2020-08-31 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('lenght', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='ShowHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Hall')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Pricing')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payed', models.BooleanField()),
                ('mail', models.CharField(max_length=100)),
                ('ukey', models.BooleanField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Place')),
                ('showHall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ShowHall')),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiere', models.DateField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
